/*
** Inserted at beginning of c files generated by bison
** REMEMBER:  Change bison.reset too.
*/

/*@-allmacros@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macroparams@*/
/*@-macroundef@*/
/*@-unreachable@*/
/*@-macrospec@*/
/*@-varuse@*/
/*@+ignorequals@*/
/*@-macrostmt@*/
/*@-noeffect@*/
/*@-shadow@*/
/*@-exitarg@*/
/*@-macroredef@*/
/*@-uniondef@*/
/*@-compdef@*/
/*@-matchfields@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-typeuse@*/
/*@-redecl@*/
/*@-redef@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-fielduse@*/
/*@-ifblock@*/
/*@-elseifcomplete@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-branchstate@*/
/*@-readonlytrans@*/
/*@-namechecks@*/
/*@-usedef@*/
/*@-systemunrecog@*/
/*@-dependenttrans@*/
/*@-unqualifiedtrans@*/
/*@-nullassign@*/
/*@-nullpass@*/
/*@-nullptrarith*/
/*@-usereleased@*/
/*@-declundef@*/

/*drl added 11/27/2001*/
/*@-bounds@*/

/*drl added 12/11/2002*/
/*@-type@*/

/* < end of bison.head > */

#ifndef BISON_CGRAMMAR_TAB_H
# define BISON_CGRAMMAR_TAB_H

#ifndef cgrammar_YYSTYPE
typedef union
{
  lltok tok;
  int count;
  qual typequal;
  qualList tquallist;
  ctype ctyp;
  /*@dependent@*/ sRef sr;
  /*@only@*/ sRef osr;

  /*@only@*/ functionClauseList funcclauselist;
  /*@only@*/ functionClause funcclause;  
  /*@only@*/ flagSpec flagspec;
  /*@only@*/ globalsClause globsclause;
  /*@only@*/ modifiesClause modsclause;
  /*@only@*/ warnClause warnclause;
  /*@only@*/ stateClause stateclause;
  /*@only@*/ pointers pointers;
  /*@only@*/ functionConstraint fcnconstraint; 

  /*@only@*/ metaStateConstraint msconstraint;
  /*@only@*/ metaStateSpecifier msspec;
  /*@only@*/ metaStateExpression msexpr;
  /*@observer@*/ metaStateInfo msinfo;

  /*@only@*/ sRefList srlist;
  /*@only@*/ globSet globset;
  /*@only@*/ qtype qtyp;
  /*@only@*/ cstring cname;
  /*@observer@*/ annotationInfo annotation;
  /*@only@*/ idDecl ntyp;
  /*@only@*/ idDeclList ntyplist;
  /*@only@*/ uentryList flist;
  /*@owned@*/ uentryList entrylist;
  /*@observer@*/ /*@dependent@*/ uentry entry;
  /*@only@*/ uentry oentry;
  /*@only@*/ exprNode expr;
  /*@only@*/ enumNameList enumnamelist;
  /*@only@*/ exprNodeList exprlist;
  /*@only@*/ sRefSet srset; 
  /*@only@*/ cstringList cstringlist;

  /*drl
    added 1/19/2001
  */
  constraint con;
  constraintList conL;
  constraintExpr conE;
  /* drl */  
} yystype;
# define cgrammar_YYSTYPE yystype
# define cgrammar_YYSTYPE_IS_TRIVIAL 1
#endif
# define	BADTOK	257
# define	SKIPTOK	258
# define	CTOK_ELIPSIS	259
# define	CASE	260
# define	DEFAULT	261
# define	CIF	262
# define	CELSE	263
# define	SWITCH	264
# define	WHILE	265
# define	DO	266
# define	CFOR	267
# define	GOTO	268
# define	CONTINUE	269
# define	BREAK	270
# define	RETURN	271
# define	TSEMI	272
# define	TLBRACE	273
# define	TRBRACE	274
# define	TCOMMA	275
# define	TCOLON	276
# define	TASSIGN	277
# define	TLPAREN	278
# define	TRPAREN	279
# define	TLSQBR	280
# define	TRSQBR	281
# define	TDOT	282
# define	TAMPERSAND	283
# define	TEXCL	284
# define	TTILDE	285
# define	TMINUS	286
# define	TPLUS	287
# define	TMULT	288
# define	TDIV	289
# define	TPERCENT	290
# define	TLT	291
# define	TGT	292
# define	TCIRC	293
# define	TBAR	294
# define	TQUEST	295
# define	CSIZEOF	296
# define	CALIGNOF	297
# define	CTYPEOF	298
# define	ARROW_OP	299
# define	CTYPEDEF	300
# define	COFFSETOF	301
# define	INC_OP	302
# define	DEC_OP	303
# define	LEFT_OP	304
# define	RIGHT_OP	305
# define	LE_OP	306
# define	GE_OP	307
# define	EQ_OP	308
# define	NE_OP	309
# define	AND_OP	310
# define	OR_OP	311
# define	MUL_ASSIGN	312
# define	DIV_ASSIGN	313
# define	MOD_ASSIGN	314
# define	ADD_ASSIGN	315
# define	SUB_ASSIGN	316
# define	LEFT_ASSIGN	317
# define	RIGHT_ASSIGN	318
# define	AND_ASSIGN	319
# define	XOR_ASSIGN	320
# define	OR_ASSIGN	321
# define	CSTRUCT	322
# define	CUNION	323
# define	CENUM	324
# define	VA_ARG	325
# define	VA_DCL	326
# define	QWARN	327
# define	QGLOBALS	328
# define	QMODIFIES	329
# define	QNOMODS	330
# define	QCONSTANT	331
# define	QFUNCTION	332
# define	QITER	333
# define	QDEFINES	334
# define	QUSES	335
# define	QALLOCATES	336
# define	QSETS	337
# define	QRELEASES	338
# define	QPRECLAUSE	339
# define	QPOSTCLAUSE	340
# define	QINVARIANT	341
# define	QALT	342
# define	QUNDEF	343
# define	QKILLED	344
# define	QENDMACRO	345
# define	LLMACRO	346
# define	LLMACROITER	347
# define	LLMACROEND	348
# define	TENDMACRO	349
# define	QSWITCHBREAK	350
# define	QLOOPBREAK	351
# define	QINNERBREAK	352
# define	QSAFEBREAK	353
# define	QINNERCONTINUE	354
# define	QFALLTHROUGH	355
# define	QLINTNOTREACHED	356
# define	QLINTFALLTHROUGH	357
# define	QLINTFALLTHRU	358
# define	QARGSUSED	359
# define	QPRINTFLIKE	360
# define	QLINTPRINTFLIKE	361
# define	QSCANFLIKE	362
# define	QMESSAGELIKE	363
# define	QNOTREACHED	364
# define	QCONST	365
# define	QRESTRICT	366
# define	QVOLATILE	367
# define	QINLINE	368
# define	QEXTENSION	369
# define	QEXTERN	370
# define	QSTATIC	371
# define	QAUTO	372
# define	QREGISTER	373
# define	QOUT	374
# define	QIN	375
# define	QYIELD	376
# define	QONLY	377
# define	QTEMP	378
# define	QSHARED	379
# define	QREF	380
# define	QUNIQUE	381
# define	QCHECKED	382
# define	QUNCHECKED	383
# define	QCHECKEDSTRICT	384
# define	QCHECKMOD	385
# define	QKEEP	386
# define	QKEPT	387
# define	QPARTIAL	388
# define	QSPECIAL	389
# define	QOWNED	390
# define	QDEPENDENT	391
# define	QRETURNED	392
# define	QEXPOSED	393
# define	QNULL	394
# define	QOBSERVER	395
# define	QISNULL	396
# define	QEXITS	397
# define	QMAYEXIT	398
# define	QNEVEREXIT	399
# define	QTRUEEXIT	400
# define	QFALSEEXIT	401
# define	QLONG	402
# define	QSIGNED	403
# define	QUNSIGNED	404
# define	QSHORT	405
# define	QUNUSED	406
# define	QSEF	407
# define	QNOTNULL	408
# define	QRELNULL	409
# define	QABSTRACT	410
# define	QNUMABSTRACT	411
# define	QCONCRETE	412
# define	QMUTABLE	413
# define	QIMMUTABLE	414
# define	QTRUENULL	415
# define	QFALSENULL	416
# define	QEXTERNAL	417
# define	QREFCOUNTED	418
# define	QREFS	419
# define	QNEWREF	420
# define	QTEMPREF	421
# define	QKILLREF	422
# define	QRELDEF	423
# define	CGCHAR	424
# define	CBOOL	425
# define	CINT	426
# define	CGFLOAT	427
# define	CDOUBLE	428
# define	CVOID	429
# define	QANYTYPE	430
# define	QINTEGRALTYPE	431
# define	QUNSIGNEDINTEGRALTYPE	432
# define	QSIGNEDINTEGRALTYPE	433
# define	QNULLTERMINATED	434
# define	QSETBUFFERSIZE	435
# define	QSETSTRINGLENGTH	436
# define	QMAXSET	437
# define	QMAXREAD	438
# define	QTESTINRANGE	439
# define	TCAND	440
# define	IDENTIFIER	441
# define	NEW_IDENTIFIER	442
# define	TYPE_NAME_OR_ID	443
# define	CANNOTATION	444
# define	CCONSTANT	445
# define	ITER_NAME	446
# define	ITER_ENDNAME	447
# define	TYPE_NAME	448
# define	METASTATE_NAME	449


extern cgrammar_YYSTYPE yylval;

#endif /* not BISON_CGRAMMAR_TAB_H */
/*
** Resets all flags in bison.head
*/


/*@=allmacros@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macroparams@*/
/*@=macroundef@*/
/*@=unreachable@*/
/*@=macrospec@*/
/*@=varuse@*/
/*@=ignorequals@*/
/*@=macrostmt@*/
/*@=noeffect@*/
/*@=shadow@*/
/*@=exitarg@*/
/*@=macroredef@*/
/*@=uniondef@*/
/*@=compdef@*/
/*@=matchfields@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=typeuse@*/
/*@=redecl@*/
/*@=redef@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=fielduse@*/
/*@=ifblock@*/
/*@=elseifcomplete@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=branchstate@*/
/*@=readonlytrans@*/
/*@=namechecks@*/
/*@=usedef@*/
/*@=systemunrecog@*/
/*@=dependenttrans@*/
/*@=unqualifiedtrans@*/
/*@=declundef@*/


/*drl added 11/27/2001*/
/*@=bounds@*/

/*drl added 12/11/2002*/
/*@=type@*/
