/*
** Inserted at beginning of c files generated by bison
** REMEMBER:  Change bison.reset too.
*/

/*@-allmacros@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macroparams@*/
/*@-macroundef@*/
/*@-unreachable@*/
/*@-macrospec@*/
/*@-varuse@*/
/*@+ignorequals@*/
/*@-macrostmt@*/
/*@-noeffect@*/
/*@-shadow@*/
/*@-exitarg@*/
/*@-macroredef@*/
/*@-uniondef@*/
/*@-compdef@*/
/*@-matchfields@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-typeuse@*/
/*@-redecl@*/
/*@-redef@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-fielduse@*/
/*@-ifblock@*/
/*@-elseifcomplete@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-branchstate@*/
/*@-readonlytrans@*/
/*@-namechecks@*/
/*@-usedef@*/
/*@-systemunrecog@*/
/*@-dependenttrans@*/
/*@-unqualifiedtrans@*/
/*@-nullassign@*/
/*@-declundef@*/

/* < end of bison.head > */

typedef union {
  mttok tok; 
  mtDeclarationNode mtdecl;
  mtDeclarationPiece mtpiece;
  mtDeclarationPieces mtpieces;
  mtContextNode mtcontext;
  mtValuesNode mtvalues;
  mtDefaultsNode mtdefaults;
  mtDefaultsDeclList mtdeflist;
  mtAnnotationsNode mtannotations;
  mtAnnotationList mtannotlist;
  mtAnnotationDecl mtannotdecl;
  mtMergeNode mtmerge;
  mtMergeItem mtmergeitem;
  mtMergeClauseList mtmergeclauselist;
  mtMergeClause mtmergeclause;
  mtTransferClauseList mttransferclauselist;
  mtTransferClause mttransferclause;
  mtTransferAction mttransferaction;
  mtLoseReferenceList mtlosereferencelist;
  mtLoseReference mtlosereference;

  /*@only@*/ cstringList cstringlist;
  ctype ctyp;
  /*@only@*/ qtype qtyp;
  int count;
} YYSTYPE;
#define	MT_BADTOK	257
#define	MT_END	258
#define	MT_STATE	259
#define	MT_GLOBAL	260
#define	MT_CONTEXT	261
#define	MT_ONEOF	262
#define	MT_DEFAULTS	263
#define	MT_DEFAULT	264
#define	MT_REFERENCE	265
#define	MT_PARAMETER	266
#define	MT_RESULT	267
#define	MT_CLAUSE	268
#define	MT_ANNOTATIONS	269
#define	MT_ARROW	270
#define	MT_MERGE	271
#define	MT_TRANSFERS	272
#define	MT_PRECONDITIONS	273
#define	MT_POSTCONDITIONS	274
#define	MT_LOSEREFERENCE	275
#define	MT_AS	276
#define	MT_ERROR	277
#define	MT_PLUS	278
#define	MT_STAR	279
#define	MT_BAR	280
#define	MT_LPAREN	281
#define	MT_RPAREN	282
#define	MT_LBRACKET	283
#define	MT_RBRACKET	284
#define	MT_LBRACE	285
#define	MT_RBRACE	286
#define	MT_COMMA	287
#define	MT_CHAR	288
#define	MT_INT	289
#define	MT_FLOAT	290
#define	MT_DOUBLE	291
#define	MT_VOID	292
#define	MT_ANYTYPE	293
#define	MT_INTEGRALTYPE	294
#define	MT_UNSIGNEDINTEGRALTYPE	295
#define	MT_SIGNEDINTEGRALTYPE	296
#define	MT_CONST	297
#define	MT_VOLATILE	298
#define	MT_STRINGLIT	299
#define	MT_IDENT	300

/*
** Resets all flags in bison.head
*/


/*@=allmacros@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macroparams@*/
/*@=macroundef@*/
/*@=unreachable@*/
/*@=macrospec@*/
/*@=varuse@*/
/*@=ignorequals@*/
/*@=macrostmt@*/
/*@=noeffect@*/
/*@=shadow@*/
/*@=exitarg@*/
/*@=macroredef@*/
/*@=uniondef@*/
/*@=compdef@*/
/*@=matchfields@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=typeuse@*/
/*@=redecl@*/
/*@=redef@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=fielduse@*/
/*@=ifblock@*/
/*@=elseifcomplete@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=branchstate@*/
/*@=readonlytrans@*/
/*@=namechecks@*/
/*@=usedef@*/
/*@=systemunrecog@*/
/*@=dependenttrans@*/
/*@=unqualifiedtrans@*/
/*@=declundef@*/
