/*
** Inserted at beginning of c files generated by bison
** REMEMBER:  Change bison.reset too.
*/

/*@-allmacros@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macroparams@*/
/*@-macroundef@*/
/*@-unreachable@*/
/*@-macrospec@*/
/*@-varuse@*/
/*@+ignorequals@*/
/*@-macrostmt@*/
/*@-noeffect@*/
/*@-shadow@*/
/*@-exitarg@*/
/*@-macroredef@*/
/*@-uniondef@*/
/*@-compdef@*/
/*@-matchfields@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-typeuse@*/
/*@-redecl@*/
/*@-redef@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-fielduse@*/
/*@-ifblock@*/
/*@-elseifcomplete@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-branchstate@*/
/*@-readonlytrans@*/
/*@-namechecks@*/
/*@-usedef@*/
/*@-systemunrecog@*/
/*@-dependenttrans@*/
/*@-unqualifiedtrans@*/
/*@-nullassign@*/
/*@-nullpass@*/
/*@-nullptrarith*/
/*@-usereleased@*/
/*@-declundef@*/

/*drl added 11/27/2001*/
/*@-bounds@*/
/* < end of bison.head > */


/*  A Bison parser, made from mtgrammar.y
    by GNU Bison version 1.28  */

#define YYBISON 1  /* Identify Bison output.  */

#define yyparse mtparse
#define yylex mtlex
#define yyerror mterror
#define yylval mtlval
#define yychar mtchar
#define yydebug mtdebug
#define yynerrs mtnerrs
#define	MT_BADTOK	257
#define	MT_END	258
#define	MT_STATE	259
#define	MT_GLOBAL	260
#define	MT_CONTEXT	261
#define	MT_ONEOF	262
#define	MT_DEFAULTS	263
#define	MT_DEFAULT	264
#define	MT_REFERENCE	265
#define	MT_PARAMETER	266
#define	MT_RESULT	267
#define	MT_CLAUSE	268
#define	MT_LITERAL	269
#define	MT_NULL	270
#define	MT_ANNOTATIONS	271
#define	MT_ARROW	272
#define	MT_MERGE	273
#define	MT_TRANSFERS	274
#define	MT_PRECONDITIONS	275
#define	MT_POSTCONDITIONS	276
#define	MT_LOSEREFERENCE	277
#define	MT_AS	278
#define	MT_ERROR	279
#define	MT_PLUS	280
#define	MT_STAR	281
#define	MT_BAR	282
#define	MT_LPAREN	283
#define	MT_RPAREN	284
#define	MT_LBRACKET	285
#define	MT_RBRACKET	286
#define	MT_LBRACE	287
#define	MT_RBRACE	288
#define	MT_COMMA	289
#define	MT_CHAR	290
#define	MT_INT	291
#define	MT_FLOAT	292
#define	MT_DOUBLE	293
#define	MT_VOID	294
#define	MT_ANYTYPE	295
#define	MT_INTEGRALTYPE	296
#define	MT_UNSIGNEDINTEGRALTYPE	297
#define	MT_SIGNEDINTEGRALTYPE	298
#define	MT_CONST	299
#define	MT_VOLATILE	300
#define	MT_STRINGLIT	301
#define	MT_IDENT	302



# include "bison.reset"
# include "lclintMacros.nf"
# include "llbasic.h"

# ifndef S_SPLINT_S
extern ctype mtscanner_lookupType (mttok p_tok) /*@modifies p_tok@*/ ;
# endif

  /*@i523@*/ /* can't include these here
    # include "mtgrammar.h"
    # include "mtscanner.h"
  */

static /*@exits@*/ void mterror (char *);

/*@-noparams@*/ /* Can't list params since YYSTYPE isn't defined yet. */
static void yyprint (/*FILE *p_file, int p_type, YYSTYPE p_value */);
/*@=noparams@*/

# define YYPRINT(file, type, value) yyprint (file, type, value)

# define YYDEBUG 1

# include "bison.head"


typedef union {
  mttok tok; 
  mtDeclarationNode mtdecl;
  mtDeclarationPiece mtpiece;
  mtDeclarationPieces mtpieces;
  mtContextNode mtcontext;
  mtValuesNode mtvalues;
  mtDefaultsNode mtdefaults;
  mtDefaultsDeclList mtdeflist;
  mtAnnotationsNode mtannotations;
  mtAnnotationList mtannotlist;
  mtAnnotationDecl mtannotdecl;
  mtMergeNode mtmerge;
  mtMergeItem mtmergeitem;
  mtMergeClauseList mtmergeclauselist;
  mtMergeClause mtmergeclause;
  mtTransferClauseList mttransferclauselist;
  mtTransferClause mttransferclause;
  mtTransferAction mttransferaction;
  mtLoseReferenceList mtlosereferencelist;
  mtLoseReference mtlosereference;

  /*@only@*/ cstringList cstringlist;
  ctype ctyp;
  /*@only@*/ qtype qtyp;
  int count;
} YYSTYPE;
#ifndef YYDEBUG
#define YYDEBUG 1
#endif

#include <stdio.h>

#ifndef __cplusplus
#ifndef __STDC__
#define const
#endif
#endif



#define	YYFINAL		135
#define	YYFLAG		-32768
#define	YYNTBASE	49

#define YYTRANSLATE(x) ((unsigned)(x) <= 302 ? yytranslate[x] : 92)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     3,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    45,    46,
    47,    48
};

#if YYDEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     3,     7,    12,    15,    16,    19,    21,    23,
    25,    27,    29,    31,    33,    35,    37,    39,    42,    43,
    45,    48,    51,    54,    57,    60,    63,    64,    66,    68,
    71,    73,    77,    80,    81,    83,    85,    87,    90,    92,
    95,    98,   102,   104,   106,   108,   111,   115,   118,   122,
   124,   126,   128,   130,   132,   134,   136,   138,   140,   142,
   144,   147,   149,   153,   156,   159,   163,   168,   171,   173,
   176,   181,   184,   186,   189,   195,   197,   199,   202,   205,
   208,   211,   213,   216,   220,   222,   225,   231,   233,   235,
   237,   240
};

static const short yyrhs[] = {    -1,
    50,     0,     5,    51,     4,     0,     6,     5,    51,     4,
     0,    48,    52,     0,     0,    53,    52,     0,    54,     0,
    69,     0,    72,     0,    71,     0,    74,     0,    77,     0,
    83,     0,    81,     0,    82,     0,    84,     0,     7,    56,
     0,     0,    56,     0,    12,    57,     0,    11,    57,     0,
    13,    57,     0,    14,    57,     0,    15,    57,     0,    16,
    57,     0,     0,    58,     0,    59,     0,    59,    62,     0,
    60,     0,    59,    28,    58,     0,    67,    61,     0,     0,
    59,     0,    63,     0,    66,     0,    63,    66,     0,    27,
     0,    27,    65,     0,    27,    63,     0,    27,    65,    63,
     0,    45,     0,    46,     0,    64,     0,    65,    64,     0,
    29,    62,    30,     0,    31,    32,     0,    66,    31,    32,
     0,    36,     0,    37,     0,    38,     0,    39,     0,    40,
     0,    41,     0,    42,     0,    43,     0,    44,     0,    68,
     0,    48,     0,     8,    70,     0,    48,     0,    48,    35,
    70,     0,    10,    91,     0,     9,    73,     0,    56,    18,
    91,     0,    56,    18,    91,    73,     0,    17,    75,     0,
    76,     0,    76,    75,     0,    48,    55,    18,    91,     0,
    19,    78,     0,    79,     0,    79,    78,     0,    80,    26,
    80,    18,    89,     0,    91,     0,    27,     0,    21,    87,
     0,    22,    87,     0,    20,    87,     0,    23,    85,     0,
    86,     0,    86,    85,     0,    91,    18,    90,     0,    88,
     0,    88,    87,     0,    91,    24,    91,    18,    89,     0,
    91,     0,    90,     0,    25,     0,    25,    47,     0,    48,
     0
};

#endif

#if YYDEBUG != 0
static const short yyrline[] = { 0,
   152,   153,   156,   158,   162,   166,   167,   171,   172,   173,
   174,   175,   176,   177,   178,   179,   180,   183,   187,   188,
   191,   192,   193,   194,   195,   196,   203,   204,   207,   208,
   211,   212,   216,   219,   220,   224,   225,   226,   229,   230,
   231,   232,   235,   236,   239,   240,   243,   244,   245,   252,
   253,   254,   255,   256,   257,   258,   259,   260,   261,   267,
   270,   273,   274,   278,   281,   284,   286,   290,   293,   294,
   298,   302,   305,   306,   309,   313,   314,   317,   320,   323,
   326,   329,   330,   333,   336,   337,   340,   344,   345,   348,
   349,   352
};
#endif


#if YYDEBUG != 0 || defined (YYERROR_VERBOSE)

static const char * const yytname[] = {   "$","error","$undefined.","MT_BADTOK",
"MT_END","MT_STATE","MT_GLOBAL","MT_CONTEXT","MT_ONEOF","MT_DEFAULTS","MT_DEFAULT",
"MT_REFERENCE","MT_PARAMETER","MT_RESULT","MT_CLAUSE","MT_LITERAL","MT_NULL",
"MT_ANNOTATIONS","MT_ARROW","MT_MERGE","MT_TRANSFERS","MT_PRECONDITIONS","MT_POSTCONDITIONS",
"MT_LOSEREFERENCE","MT_AS","MT_ERROR","MT_PLUS","MT_STAR","MT_BAR","MT_LPAREN",
"MT_RPAREN","MT_LBRACKET","MT_RBRACKET","MT_LBRACE","MT_RBRACE","MT_COMMA","MT_CHAR",
"MT_INT","MT_FLOAT","MT_DOUBLE","MT_VOID","MT_ANYTYPE","MT_INTEGRALTYPE","MT_UNSIGNEDINTEGRALTYPE",
"MT_SIGNEDINTEGRALTYPE","MT_CONST","MT_VOLATILE","MT_STRINGLIT","MT_IDENT","file",
"mtsDeclaration","declarationNode","declarationPieces","declarationPiece","contextDeclaration",
"optContextSelection","contextSelection","optType","typeExpression","completeType",
"completeTypeAux","optCompleteType","abstractDecl","pointers","innerMods","innerModsList",
"abstractDeclBase","typeSpecifier","typeName","valuesDeclaration","valuesList",
"defaultNode","defaultsDeclaration","defaultDeclarationList","annotationsDeclaration",
"annotationsDeclarationList","annotationDeclaration","mergeDeclaration","mergeClauses",
"mergeClause","mergeItem","preconditionsDeclaration","postconditionsDeclaration",
"transfersDeclaration","loseReferenceDeclaration","lostClauses","lostClause",
"transferClauses","transferClause","transferAction","errorAction","valueChoice", NULL
};
#endif

static const short yyr1[] = {     0,
    49,    49,    50,    50,    51,    52,    52,    53,    53,    53,
    53,    53,    53,    53,    53,    53,    53,    54,    55,    55,
    56,    56,    56,    56,    56,    56,    57,    57,    58,    58,
    59,    59,    60,    61,    61,    62,    62,    62,    63,    63,
    63,    63,    64,    64,    65,    65,    66,    66,    66,    67,
    67,    67,    67,    67,    67,    67,    67,    67,    67,    68,
    69,    70,    70,    71,    72,    73,    73,    74,    75,    75,
    76,    77,    78,    78,    79,    80,    80,    81,    82,    83,
    84,    85,    85,    86,    87,    87,    88,    89,    89,    90,
    90,    91
};

static const short yyr2[] = {     0,
     0,     1,     3,     4,     2,     0,     2,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     2,     0,     1,
     2,     2,     2,     2,     2,     2,     0,     1,     1,     2,
     1,     3,     2,     0,     1,     1,     1,     2,     1,     2,
     2,     3,     1,     1,     1,     2,     3,     2,     3,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     2,     1,     3,     2,     2,     3,     4,     2,     1,     2,
     4,     2,     1,     2,     5,     1,     1,     2,     2,     2,
     2,     1,     2,     3,     1,     2,     5,     1,     1,     1,
     2,     1
};

static const short yydefact[] = {     1,
     0,     0,     2,     6,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     5,     6,     8,     9,
    11,    10,    12,    13,    15,    16,    14,    17,     3,     0,
    27,    27,    27,    27,    27,    27,    18,    62,    61,     0,
    65,    92,    64,    19,    68,    69,    77,    72,    73,     0,
    76,    80,    85,     0,    78,    79,    81,    82,     0,     7,
     4,    50,    51,    52,    53,    54,    55,    56,    57,    58,
    60,    22,    28,    29,    31,    34,    59,    21,    23,    24,
    25,    26,     0,     0,     0,    20,    70,    74,     0,    86,
     0,    83,     0,    39,     0,     0,     0,    30,    36,    37,
    35,    33,    63,    66,     0,     0,     0,    90,    84,    43,
    44,    41,    45,    40,    32,     0,    48,    38,     0,    67,
    71,     0,     0,    91,    42,    46,    47,    49,    75,    89,
    88,    87,     0,     0,     0
};

static const short yydefgoto[] = {   133,
     3,     5,    17,    18,    19,    85,    40,    72,    73,    74,
    75,   102,    98,    99,   113,   114,   100,    76,    77,    20,
    39,    21,    22,    41,    23,    45,    46,    24,    48,    49,
    50,    25,    26,    27,    28,    57,    58,    52,    53,   129,
   130,    54
};

static const short yypact[] = {     4,
   -37,    35,-32768,    36,    37,   -37,    21,     2,    21,    17,
    18,   -19,    17,    17,    17,    17,-32768,    36,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    63,
   -23,   -23,   -23,   -23,   -23,   -23,-32768,    33,-32768,    51,
-32768,-32768,-32768,    21,-32768,    18,-32768,-32768,   -19,    44,
-32768,-32768,    17,    47,-32768,-32768,-32768,    17,    54,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    -5,-32768,   -23,-32768,-32768,-32768,-32768,
-32768,-32768,     2,    17,    55,-32768,-32768,-32768,   -19,-32768,
    17,-32768,    50,   -15,   -23,    20,    45,-32768,    23,    49,
    48,-32768,-32768,    21,    17,    60,    64,    38,-32768,-32768,
-32768,-32768,-32768,   -15,-32768,    53,-32768,    49,    52,-32768,
-32768,   -20,   -20,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    86,    87,-32768
};

static const short yypgoto[] = {-32768,
-32768,    82,    71,-32768,-32768,-32768,    -6,    28,    -4,    14,
-32768,-32768,    -3,   -87,   -22,-32768,    -2,-32768,-32768,-32768,
    11,-32768,-32768,    -8,-32768,    56,-32768,-32768,    57,-32768,
     9,-32768,-32768,-32768,-32768,    41,-32768,   -11,-32768,   -18,
     7,   -10
};


#define	YYLAST		113


static const short yytable[] = {    43,
    37,    51,    55,    56,   108,    59,   112,    47,     1,     2,
     4,    94,    62,    63,    64,    65,    66,    67,    68,    69,
    70,    94,    95,    96,    71,    97,   125,    42,    42,   110,
   111,    31,    32,    33,    34,    35,    36,    86,    51,     6,
    29,    90,     7,     8,     9,    10,    94,    59,    96,    38,
    97,    96,    11,    97,    12,    13,    14,    15,    16,    78,
    79,    80,    81,    82,    42,    44,    61,    83,    84,    89,
    91,    93,   105,   104,   108,    95,   117,   122,    51,   119,
   107,   123,   127,   128,   124,   134,   135,    30,    60,   101,
   115,   126,   116,   103,   121,   120,   118,   106,    92,   109,
     0,    87,     0,     0,   132,    88,     0,     0,     0,     0,
     0,   131,   131
};

static const short yycheck[] = {    10,
     7,    12,    14,    15,    25,    16,    94,    27,     5,     6,
    48,    27,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    27,    28,    29,    48,    31,   114,    48,    48,    45,
    46,    11,    12,    13,    14,    15,    16,    44,    49,     5,
     4,    53,     7,     8,     9,    10,    27,    58,    29,    48,
    31,    29,    17,    31,    19,    20,    21,    22,    23,    32,
    33,    34,    35,    36,    48,    48,     4,    35,    18,    26,
    24,    18,    18,    84,    25,    28,    32,    18,    89,    31,
    91,    18,    30,    32,    47,     0,     0,     6,    18,    76,
    95,   114,    96,    83,   105,   104,    99,    89,    58,    93,
    -1,    46,    -1,    -1,   123,    49,    -1,    -1,    -1,    -1,
    -1,   122,   123
};
#define YYPURE 1

/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */

/* This file comes from bison-1.28.  */

/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.  */

/* As a special exception, when this file is copied by Bison into a
   Bison output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison.  */

/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

#ifndef YYSTACK_USE_ALLOCA
#ifdef alloca
#define YYSTACK_USE_ALLOCA
#else /* alloca not defined */
#ifdef __GNUC__
#define YYSTACK_USE_ALLOCA
#define alloca __builtin_alloca
#else /* not GNU C.  */
#if (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc) || defined (__sgi) || (defined (__sun) && defined (__i386))
#define YYSTACK_USE_ALLOCA
#include <alloca.h>
#else /* not sparc */
/* We think this test detects Watcom and Microsoft C.  */
/* This used to test MSDOS, but that is a bad idea
   since that symbol is in the user namespace.  */
#if (defined (_MSDOS) || defined (_MSDOS_)) && !defined (__TURBOC__)
#if 0 /* No need for malloc.h, which pollutes the namespace;
	 instead, just don't use alloca.  */
#include <malloc.h>
#endif
#else /* not MSDOS, or __TURBOC__ */
#if defined(_AIX)
/* I don't know what this was needed for, but it pollutes the namespace.
   So I turned it off.   rms, 2 May 1997.  */
/* #include <malloc.h>  */
 #pragma alloca
#define YYSTACK_USE_ALLOCA
#else /* not MSDOS, or __TURBOC__, or _AIX */
#if 0
#ifdef __hpux /* haible@ilog.fr says this works for HPUX 9.05 and up,
		 and on HPUX 10.  Eventually we can turn this on.  */
#define YYSTACK_USE_ALLOCA
#define alloca __builtin_alloca
#endif /* __hpux */
#endif
#endif /* not _AIX */
#endif /* not MSDOS, or __TURBOC__ */
#endif /* not sparc */
#endif /* not GNU C */
#endif /* alloca not defined */
#endif /* YYSTACK_USE_ALLOCA not defined */

#ifdef YYSTACK_USE_ALLOCA
#define YYSTACK_ALLOC alloca
#else
#define YYSTACK_ALLOC malloc
#endif

/* Note: there must be only one dollar sign in this file.
   It is replaced by the list of actions, each action
   as one case of the switch.  */

#define yyerrok		(yyerrstatus = 0)
#define yyclearin	(yychar = YYEMPTY)
#define YYEMPTY		-2
#define YYEOF		0
#define YYACCEPT	goto yyacceptlab
#define YYABORT 	goto yyabortlab
#define YYERROR		goto yyerrlab1
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL		goto yyerrlab
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do								\
  if (yychar == YYEMPTY && yylen == 1)				\
    { yychar = (token), yylval = (value);			\
      yychar1 = YYTRANSLATE (yychar);				\
      YYPOPSTACK;						\
      goto yybackup;						\
    }								\
  else								\
    { yyerror ("syntax error: cannot back up"); YYERROR; }	\
while (0)

#define YYTERROR	1
#define YYERRCODE	256

#ifndef YYPURE
#define YYLEX		yylex()
#endif

#ifdef YYPURE
#ifdef YYLSP_NEEDED
#ifdef YYLEX_PARAM
#define YYLEX		yylex(&yylval, &yylloc, YYLEX_PARAM)
#else
#define YYLEX		yylex(&yylval, &yylloc)
#endif
#else /* not YYLSP_NEEDED */
#ifdef YYLEX_PARAM
#define YYLEX		yylex(&yylval, YYLEX_PARAM)
#else
#define YYLEX		yylex(&yylval)
#endif
#endif /* not YYLSP_NEEDED */
#endif

/* If nonreentrant, generate the variables here */

#ifndef YYPURE

int	yychar;			/*  the lookahead symbol		*/
YYSTYPE	yylval;			/*  the semantic value of the		*/
				/*  lookahead symbol			*/

#ifdef YYLSP_NEEDED
YYLTYPE yylloc;			/*  location data for the lookahead	*/
				/*  symbol				*/
#endif

int yynerrs;			/*  number of parse errors so far       */
#endif  /* not YYPURE */

#if YYDEBUG != 0
int yydebug;			/*  nonzero means print parse trace	*/
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif

/*  YYINITDEPTH indicates the initial size of the parser's stacks	*/

#ifndef	YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif

/* Define __yy_memcpy.  Note that the size argument
   should be passed with type unsigned int, because that is what the non-GCC
   definitions require.  With GCC, __builtin_memcpy takes an arg
   of type size_t, but it can handle unsigned int.  */

#if __GNUC__ > 1		/* GNU C and GNU C++ define this.  */
#define __yy_memcpy(TO,FROM,COUNT)	__builtin_memcpy(TO,FROM,COUNT)
#else				/* not GNU C or C++ */
#ifndef __cplusplus

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */
static void
__yy_memcpy (to, from, count)
     char *to;
     char *from;
     unsigned int count;
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}

#else /* __cplusplus */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */
static void
__yy_memcpy (char *to, char *from, unsigned int count)
{
  register char *t = to;
  register char *f = from;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}

#endif
#endif



/* The user can define YYPARSE_PARAM as the name of an argument to be passed
   into yyparse.  The argument should have type void *.
   It should actually point to an object.
   Grammar actions can access the variable by casting it
   to the proper pointer type.  */

#ifdef YYPARSE_PARAM
#ifdef __cplusplus
#define YYPARSE_PARAM_ARG void *YYPARSE_PARAM
#define YYPARSE_PARAM_DECL
#else /* not __cplusplus */
#define YYPARSE_PARAM_ARG YYPARSE_PARAM
#define YYPARSE_PARAM_DECL void *YYPARSE_PARAM;
#endif /* not __cplusplus */
#else /* not YYPARSE_PARAM */
#define YYPARSE_PARAM_ARG
#define YYPARSE_PARAM_DECL
#endif /* not YYPARSE_PARAM */

/* Prevent warning if -Wstrict-prototypes.  */
#ifdef __GNUC__
#ifdef YYPARSE_PARAM
int yyparse (void *);
#else
int yyparse (void);
#endif
#endif

int
yyparse(YYPARSE_PARAM_ARG)
     YYPARSE_PARAM_DECL
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YYSTYPE *yyvsp;
  int yyerrstatus;	/*  number of tokens to shift before error messages enabled */
  int yychar1 = 0;		/*  lookahead token as an internal (translated) token number */

  short	yyssa[YYINITDEPTH];	/*  the state stack			*/
  YYSTYPE yyvsa[YYINITDEPTH];	/*  the semantic value stack		*/

  short *yyss = yyssa;		/*  refer to the stacks thru separate pointers */
  YYSTYPE *yyvs = yyvsa;	/*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YYLSP_NEEDED
  YYLTYPE yylsa[YYINITDEPTH];	/*  the location stack			*/
  YYLTYPE *yyls = yylsa;
  YYLTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;
  int yyfree_stacks = 0;

#ifdef YYPURE
  int yychar;
  YYSTYPE yylval;
  int yynerrs;
#ifdef YYLSP_NEEDED
  YYLTYPE yylloc;
#endif
#endif

  YYSTYPE yyval;		/*  the variable used to return		*/
				/*  semantic values from the action	*/
				/*  routines				*/

  int yylen;

#if YYDEBUG != 0
  if (yydebug)
    fprintf(stderr, "Starting parse\n");
#endif

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY;		/* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YYLSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
yynewstate:

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YYSTYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YYLSP_NEEDED
      YYLTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YYLSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YYLSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  yyerror("parser stack overflow");
	  if (yyfree_stacks)
	    {
	      free (yyss);
	      free (yyvs);
#ifdef YYLSP_NEEDED
	      free (yyls);
#endif
	    }
	  return 2;
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
#ifndef YYSTACK_USE_ALLOCA
      yyfree_stacks = 1;
#endif
      yyss = (short *) YYSTACK_ALLOC (yystacksize * sizeof (*yyssp));
      __yy_memcpy ((char *)yyss, (char *)yyss1,
		   size * (unsigned int) sizeof (*yyssp));
      yyvs = (YYSTYPE *) YYSTACK_ALLOC (yystacksize * sizeof (*yyvsp));
      __yy_memcpy ((char *)yyvs, (char *)yyvs1,
		   size * (unsigned int) sizeof (*yyvsp));
#ifdef YYLSP_NEEDED
      yyls = (YYLTYPE *) YYSTACK_ALLOC (yystacksize * sizeof (*yylsp));
      __yy_memcpy ((char *)yyls, (char *)yyls1,
		   size * (unsigned int) sizeof (*yylsp));
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YYLSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YYDEBUG != 0
      if (yydebug)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YYDEBUG != 0
  if (yydebug)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  goto yybackup;
 yybackup:

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* yyresume: */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (yychar == YYEMPTY)
    {
#if YYDEBUG != 0
      if (yydebug)
	fprintf(stderr, "Reading a token: ");
#endif
      yychar = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (yychar <= 0)		/* This means end of input. */
    {
      yychar1 = 0;
      yychar = YYEOF;		/* Don't call YYLEX any more */

#if YYDEBUG != 0
      if (yydebug)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(yychar);

#if YYDEBUG != 0
      if (yydebug)
	{
	  fprintf (stderr, "Next token is %d (%s", yychar, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, yychar, yylval);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    goto yydefault;

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }
  else if (yyn == 0)
    goto yyerrlab;

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YYDEBUG != 0
  if (yydebug)
    fprintf(stderr, "Shifting token %d (%s), ", yychar, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (yychar != YYEOF)
    yychar = YYEMPTY;

  *++yyvsp = yylval;
#ifdef YYLSP_NEEDED
  *++yylsp = yylloc;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  goto yynewstate;

/* Do the default action for the current state.  */
yydefault:

  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
yyreduce:
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YYDEBUG != 0
  if (yydebug)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


  switch (yyn) {

case 1:
{;
    break;}
case 2:
{;
    break;}
case 3:
{ mtreader_processDeclaration (yyvsp[-1].mtdecl); ;
    break;}
case 4:
{ mtreader_processGlobalDeclaration (yyvsp[-1].mtdecl); ;
    break;}
case 5:
{ yyval.mtdecl = mtDeclarationNode_create (yyvsp[-1].tok, yyvsp[0].mtpieces); ;
    break;}
case 6:
{ yyval.mtpieces = mtDeclarationPieces_create (); ;
    break;}
case 7:
{ yyval.mtpieces = mtDeclarationPieces_append (yyvsp[0].mtpieces, yyvsp[-1].mtpiece); ;
    break;}
case 8:
{ yyval.mtpiece = mtDeclarationPiece_createContext (yyvsp[0].mtcontext); ;
    break;}
case 9:
{ yyval.mtpiece = mtDeclarationPiece_createValues (yyvsp[0].mtvalues); ;
    break;}
case 10:
{ yyval.mtpiece = mtDeclarationPiece_createDefaults (yyvsp[0].mtdefaults); ;
    break;}
case 11:
{ yyval.mtpiece = mtDeclarationPiece_createValueDefault (yyvsp[0].tok); ;
    break;}
case 12:
{ yyval.mtpiece = mtDeclarationPiece_createAnnotations (yyvsp[0].mtannotations); ;
    break;}
case 13:
{ yyval.mtpiece = mtDeclarationPiece_createMerge (yyvsp[0].mtmerge); ;
    break;}
case 14:
{ yyval.mtpiece = mtDeclarationPiece_createTransfers (yyvsp[0].mttransferclauselist); ;
    break;}
case 15:
{ yyval.mtpiece = mtDeclarationPiece_createPreconditions (yyvsp[0].mttransferclauselist); ;
    break;}
case 16:
{ yyval.mtpiece = mtDeclarationPiece_createPostconditions (yyvsp[0].mttransferclauselist); ;
    break;}
case 17:
{ yyval.mtpiece = mtDeclarationPiece_createLosers (yyvsp[0].mtlosereferencelist); ;
    break;}
case 18:
{ yyval.mtcontext = yyvsp[0].mtcontext; ;
    break;}
case 19:
{ yyval.mtcontext = mtContextNode_createAny (); ;
    break;}
case 21:
{ yyval.mtcontext = mtContextNode_createParameter (yyvsp[0].ctyp); ;
    break;}
case 22:
{ yyval.mtcontext = mtContextNode_createReference (yyvsp[0].ctyp); ;
    break;}
case 23:
{ yyval.mtcontext = mtContextNode_createResult (yyvsp[0].ctyp); ;
    break;}
case 24:
{ yyval.mtcontext = mtContextNode_createClause (yyvsp[0].ctyp); ;
    break;}
case 25:
{ yyval.mtcontext = mtContextNode_createLiteral (yyvsp[0].ctyp); ;
    break;}
case 26:
{ yyval.mtcontext = mtContextNode_createNull (yyvsp[0].ctyp); ;
    break;}
case 27:
{ yyval.ctyp = ctype_unknown; ;
    break;}
case 28:
{ DPRINTF (("Type: %s", qtype_unparse (yyvsp[0].qtyp))); yyval.ctyp = qtype_getType (yyvsp[0].qtyp); ;
    break;}
case 30:
{ yyval.qtyp = qtype_newBase (yyvsp[-1].qtyp, yyvsp[0].ctyp); ;
    break;}
case 31:
{ yyval.qtyp = yyvsp[0].qtyp; ;
    break;}
case 32:
{ yyval.qtyp = qtype_mergeAlt (yyvsp[-2].qtyp, yyvsp[0].qtyp); ;
    break;}
case 33:
{ yyval.qtyp = qtype_combine (yyvsp[0].qtyp, yyvsp[-1].ctyp); ;
    break;}
case 34:
{ yyval.qtyp = qtype_unknown (); ;
    break;}
case 35:
{ yyval.qtyp = yyvsp[0].qtyp; ;
    break;}
case 36:
{ yyval.ctyp = ctype_adjustPointers (yyvsp[0].count, ctype_unknown); ;
    break;}
case 38:
{ yyval.ctyp = ctype_adjustPointers (yyvsp[-1].count, yyvsp[0].ctyp); ;
    break;}
case 39:
{ yyval.count = 1; ;
    break;}
case 40:
{ yyval.count = 1; ;
    break;}
case 41:
{ yyval.count = 1 + yyvsp[0].count; ;
    break;}
case 42:
{ yyval.count = 1 + yyvsp[0].count; ;
    break;}
case 43:
{ /* ignored for now */; ;
    break;}
case 44:
{ ; ;
    break;}
case 45:
{ ; ;
    break;}
case 46:
{ ; ;
    break;}
case 47:
{ yyval.ctyp = ctype_expectFunction (yyvsp[-1].ctyp); ;
    break;}
case 48:
{ yyval.ctyp = ctype_makeArray (ctype_unknown); ;
    break;}
case 49:
{ yyval.ctyp = ctype_makeArray (yyvsp[-2].ctyp); ;
    break;}
case 50:
{ yyval.ctyp = ctype_char; ;
    break;}
case 51:
{ yyval.ctyp = ctype_int; ;
    break;}
case 52:
{ yyval.ctyp = ctype_float; ;
    break;}
case 53:
{ yyval.ctyp = ctype_double; ;
    break;}
case 54:
{ yyval.ctyp = ctype_void; ;
    break;}
case 55:
{ yyval.ctyp = ctype_unknown; ;
    break;}
case 56:
{ yyval.ctyp = ctype_anyintegral; ;
    break;}
case 57:
{ yyval.ctyp = ctype_unsignedintegral; ;
    break;}
case 58:
{ yyval.ctyp = ctype_signedintegral; ;
    break;}
case 60:
{ yyval.ctyp = mtscanner_lookupType (yyvsp[0].tok); ;
    break;}
case 61:
{ yyval.mtvalues = mtValuesNode_create (yyvsp[0].cstringlist); ;
    break;}
case 62:
{ yyval.cstringlist = cstringList_single (mttok_getText (yyvsp[0].tok)); ;
    break;}
case 63:
{ yyval.cstringlist = cstringList_prepend (yyvsp[0].cstringlist, mttok_getText (yyvsp[-2].tok)); ;
    break;}
case 64:
{ yyval.tok = yyvsp[0].tok; ;
    break;}
case 65:
{ yyval.mtdefaults = mtDefaultsNode_create (yyvsp[-1].tok, yyvsp[0].mtdeflist); ;
    break;}
case 66:
{ yyval.mtdeflist = mtDefaultsDeclList_single (mtDefaultsDecl_create (yyvsp[-2].mtcontext, yyvsp[0].tok)); ;
    break;}
case 67:
{ yyval.mtdeflist = mtDefaultsDeclList_prepend (yyvsp[0].mtdeflist, mtDefaultsDecl_create (yyvsp[-3].mtcontext, yyvsp[-1].tok)); ;
    break;}
case 68:
{ yyval.mtannotations = mtAnnotationsNode_create (yyvsp[0].mtannotlist); ;
    break;}
case 69:
{ yyval.mtannotlist = mtAnnotationList_single (yyvsp[0].mtannotdecl); ;
    break;}
case 70:
{ yyval.mtannotlist = mtAnnotationList_prepend (yyvsp[0].mtannotlist, yyvsp[-1].mtannotdecl); ;
    break;}
case 71:
{ yyval.mtannotdecl = mtAnnotationDecl_create (yyvsp[-3].tok, yyvsp[-2].mtcontext, yyvsp[0].tok); ;
    break;}
case 72:
{ yyval.mtmerge = mtMergeNode_create (yyvsp[0].mtmergeclauselist); ;
    break;}
case 73:
{ yyval.mtmergeclauselist = mtMergeClauseList_single (yyvsp[0].mtmergeclause); ;
    break;}
case 74:
{ yyval.mtmergeclauselist = mtMergeClauseList_prepend (yyvsp[0].mtmergeclauselist, yyvsp[-1].mtmergeclause); ;
    break;}
case 75:
{ yyval.mtmergeclause = mtMergeClause_create (yyvsp[-4].mtmergeitem, yyvsp[-2].mtmergeitem, yyvsp[0].mttransferaction); ;
    break;}
case 76:
{ yyval.mtmergeitem = mtMergeItem_createValue (yyvsp[0].tok); ;
    break;}
case 77:
{ yyval.mtmergeitem = mtMergeItem_createStar (yyvsp[0].tok); ;
    break;}
case 78:
{ yyval.mttransferclauselist = yyvsp[0].mttransferclauselist; ;
    break;}
case 79:
{ yyval.mttransferclauselist = yyvsp[0].mttransferclauselist; ;
    break;}
case 80:
{ yyval.mttransferclauselist = yyvsp[0].mttransferclauselist; ;
    break;}
case 81:
{ yyval.mtlosereferencelist = yyvsp[0].mtlosereferencelist; ;
    break;}
case 82:
{ yyval.mtlosereferencelist = mtLoseReferenceList_single (yyvsp[0].mtlosereference); ;
    break;}
case 83:
{ yyval.mtlosereferencelist = mtLoseReferenceList_prepend (yyvsp[0].mtlosereferencelist, yyvsp[-1].mtlosereference); ;
    break;}
case 84:
{ yyval.mtlosereference = mtLoseReference_create (yyvsp[-2].tok, yyvsp[0].mttransferaction); ;
    break;}
case 85:
{ yyval.mttransferclauselist = mtTransferClauseList_single (yyvsp[0].mttransferclause); ;
    break;}
case 86:
{ yyval.mttransferclauselist = mtTransferClauseList_prepend (yyvsp[0].mttransferclauselist, yyvsp[-1].mttransferclause); ;
    break;}
case 87:
{ yyval.mttransferclause = mtTransferClause_create (yyvsp[-4].tok, yyvsp[-2].tok, yyvsp[0].mttransferaction); ;
    break;}
case 88:
{ yyval.mttransferaction = mtTransferAction_createValue (yyvsp[0].tok); ;
    break;}
case 89:
{ yyval.mttransferaction = yyvsp[0].mttransferaction; ;
    break;}
case 90:
{ yyval.mttransferaction = mtTransferAction_createError (yyvsp[0].tok); ;
    break;}
case 91:
{ yyval.mttransferaction = mtTransferAction_createErrorMessage (yyvsp[0].tok); ;
    break;}
}
   /* the action file gets copied in in place of this dollarsign */


  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YYLSP_NEEDED
  yylsp -= yylen;
#endif

#if YYDEBUG != 0
  if (yydebug)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YYLSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = yylloc.first_line;
      yylsp->first_column = yylloc.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  goto yynewstate;

yyerrlab:   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++yynerrs;

#ifdef YYERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      yyerror(msg);
	      free(msg);
	    }
	  else
	    yyerror ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YYERROR_VERBOSE */
	yyerror("parse error");
    }

  goto yyerrlab1;
yyerrlab1:   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (yychar == YYEOF)
	YYABORT;

#if YYDEBUG != 0
      if (yydebug)
	fprintf(stderr, "Discarding token %d (%s).\n", yychar, yytname[yychar1]);
#endif

      yychar = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;		/* Each real token shifted decrements this */

  goto yyerrhandle;

yyerrdefault:  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) goto yydefault;
#endif

yyerrpop:   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YYLSP_NEEDED
  yylsp--;
#endif

#if YYDEBUG != 0
  if (yydebug)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

yyerrhandle:

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    goto yyerrdefault;

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    goto yyerrdefault;

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	goto yyerrpop;
      yyn = -yyn;
      goto yyreduce;
    }
  else if (yyn == 0)
    goto yyerrpop;

  if (yyn == YYFINAL)
    YYACCEPT;

#if YYDEBUG != 0
  if (yydebug)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = yylval;
#ifdef YYLSP_NEEDED
  *++yylsp = yylloc;
#endif

  yystate = yyn;
  goto yynewstate;

 yyacceptlab:
  /* YYACCEPT comes here.  */
  if (yyfree_stacks)
    {
      free (yyss);
      free (yyvs);
#ifdef YYLSP_NEEDED
      free (yyls);
#endif
    }
  return 0;

 yyabortlab:
  /* YYABORT comes here.  */
  if (yyfree_stacks)
    {
      free (yyss);
      free (yyvs);
#ifdef YYLSP_NEEDED
      free (yyls);
#endif
    }
  return 1;
}


# include "bison.reset"

extern char *yytext;

static void mterror (char *s) 
{
  
  if (s != NULL)
    {
      llparseerror
	(message ("Parse error in meta-state file: %s", cstring_fromChars (s)));
    }
  else
    {
      llparseerror
	(message ("Parse error in meta-state file"));
    }

}

static void yyprint (FILE *file, int type, YYSTYPE value)
{
  cstring tname = mttok_unparse (value.tok);
  fprintf (file, " (%s)", cstring_toCharsSafe (tname));
  cstring_free (tname);
}




/*
** Resets all flags in bison.head
*/


/*@=allmacros@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macroparams@*/
/*@=macroundef@*/
/*@=unreachable@*/
/*@=macrospec@*/
/*@=varuse@*/
/*@=ignorequals@*/
/*@=macrostmt@*/
/*@=noeffect@*/
/*@=shadow@*/
/*@=exitarg@*/
/*@=macroredef@*/
/*@=uniondef@*/
/*@=compdef@*/
/*@=matchfields@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=typeuse@*/
/*@=redecl@*/
/*@=redef@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=fielduse@*/
/*@=ifblock@*/
/*@=elseifcomplete@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=branchstate@*/
/*@=readonlytrans@*/
/*@=namechecks@*/
/*@=usedef@*/
/*@=systemunrecog@*/
/*@=dependenttrans@*/
/*@=unqualifiedtrans@*/
/*@=declundef@*/


/*drl added 11/27/2001*/
/*@=bounds@*/
